[package]
name = "pagebook"
version.workspace = true
edition.workspace = true
publish.workspace = true

[lib]
crate-type = ["lib", "cdylib"]
doctest = false

[dependencies]
soroban-sdk = { workspace = true }
pagebook-types = { workspace = true }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
pagebook-types = { workspace = true, features = ["testutils"] }
proptest = "1"
pagebook-client = { workspace = true }
