import type { BookEvent, BookSnapshot } from "../book";

export type MockSnapshot = BookSnapshot & {
  events: BookEvent[];
  historyFrom: number;
};

export function mockSnapshot(): MockSnapshot {
  return {
    latestLedger: 4215102,
    mismatched: false,
    bestBid: { empty: false, tick: 99, stale: false },
    bestAsk: { empty: false, tick: 101, stale: false },
    bids: [
      {
        tick: 99,
        open_lots: 40n,
        queue: 3,
        generation: 4,
        head_seq: 0,
        depth: 3,
      },
      {
        tick: 98,
        open_lots: 25n,
        queue: 1,
        generation: 2,
        head_seq: 0,
        depth: 1,
      },
      {
        tick: 97,
        open_lots: 10n,
        queue: 2,
        generation: 1,
        head_seq: 1,
        depth: 3,
      },
    ],
    asks: [
      {
        tick: 101,
        open_lots: 12n,
        queue: 1,
        generation: 3,
        head_seq: 0,
        depth: 1,
      },
      {
        tick: 102,
        open_lots: 30n,
        queue: 2,
        generation: 1,
        head_seq: 0,
        depth: 2,
      },
      {
        tick: 104,
        open_lots: 8n,
        queue: 1,
        generation: 1,
        head_seq: 0,
        depth: 1,
      },
    ],
    market: {
      base: "CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFCT4",
      quote: "CBEC6J5RWWWC7CYCHJTXIBDFTFRK6GTMLK4E47BECO5BDXVM7YHATUIK",
      lot_size: 1n,
      tick_size: 1n,
      tick_min: 1,
      tick_max: 65536,
      taker_fee_bps: 10,
      min_order_lots: 1n,
      max_order_lots: 1000000n,
      max_levels_crossed: 32,
      level_cap: 64,
    },
    paused: false,
    vault: { base: 12340000000n, quote: 567890000000n },
    fees: { base: 70000000n, quote: 0n },
    tokens: {
      base: { symbol: "PBA", decimals: 7, name: "PageBook A" },
      quote: { symbol: "PBB", decimals: 7, name: "PageBook B" },
    },
    base: "CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFCT4",
    quote: "CBEC6J5RWWWC7CYCHJTXIBDFTFRK6GTMLK4E47BECO5BDXVM7YHATUIK",
    events: [
      {
        id: "mock-filled-1",
        name: "filled",
        ledger: 4215102,
        ledgerClosedAt: "2026-08-18T12:04:31Z",
        txHash: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
        is_bid: false,
        tick: 100,
        lots: 3n,
        quote: 300n,
        taker: "buy",
      },
      {
        id: "mock-rested-1",
        name: "rested",
        ledger: 4215102,
        ledgerClosedAt: "2026-08-18T12:04:31Z",
        txHash: "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
        owner: "GAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWHF",
        nonce: 17n,
        is_bid: true,
        tick: 99,
        generation: 4,
        seq: 2,
      },
      {
        id: "mock-filled-2",
        name: "filled",
        ledger: 4215098,
        ledgerClosedAt: "2026-08-18T12:04:26Z",
        txHash: "cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
        is_bid: true,
        tick: 99,
        lots: 5n,
        quote: 495n,
        taker: "sell",
      },
      {
        id: "mock-top-1",
        name: "top_changed",
        ledger: 4215098,
        ledgerClosedAt: "2026-08-18T12:04:26Z",
        txHash: "cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
        is_bid: false,
        old: 101,
        newTick: 102,
      },
      {
        id: "mock-settled-1",
        name: "settled",
        ledger: 4215090,
        ledgerClosedAt: "2026-08-18T12:04:10Z",
        txHash: "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd",
        owner: "GBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
        nonce: 4n,
        filled_lots: 5n,
        refunded_lots: 0n,
      },
      {
        id: "mock-swept-1",
        name: "swept",
        ledger: 4215088,
        ledgerClosedAt: "2026-08-18T12:04:05Z",
        txHash: "eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee",
        is_bid: false,
        tick: 100,
        generation: 2,
      },
    ],
    historyFrom: 4213102,
    moreBids: false,
    moreAsks: false,
  };
}
