name: ci

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.95.0
        with:
          targets: wasm32v1-none
          components: rustfmt, clippy
      - run: make lint
      - run: make test
